### ISSUE TITLE
请API添加选择frame的支持，实现wd的frame这个协议

### ISSUE THREAD

**Issue by sencho** [macacajs/macaca-wd#14]
请API添加选择frame的支持，实现wd这个协议
POST /session/:sessionId/frame
Change focus to another frame on the page.	frame(frameRef, cb) -> cb(err)

**Comment by ftvbftvbq** [comment]
还必须支持在这个frame中能够支持操作元素，操作完毕后，能够从该frame中切出来的一整套类似selenium web driver操作frame的一套完整流程。

**Comment by chenxujie1985** [comment]
貌似没有从该frame中切出来的API 可以解决下么。
