### ISSUE TITLE
macaca的api说明举例少，入门门槛有点高呀

### ISSUE THREAD

**Issue by sunada** [macacajs/macaca-wd#20]
正在调研前端自动化工具。看到macaca，想用macaca写个case。过程中就发现，api里虽然给出了基本说明，但未举例如何使用。比如：elementsByClassName  只说返回是个Array，如何从这个返回中选中某个元素未有说明。想查看源代码，发现也没有工具的原理架构图。可能对于从其他前端自动化工具迁移到macaca上的用户来说可能比较易于接受，对于小白用户，感觉还应该再丰富下api的举例。

**Comment by xudafeng** [comment]
@sunada https://github.com/macacajs/macaca-test-sample
