### ISSUE TITLE
macaca请求需要Basic Auth认证的地址时没有携带Authentication信息导致服务器返回401

### ISSUE THREAD

**Issue by megolee** [macacajs/macaca-wd#55]
服务器设置了Basic Auth认证，在脚本中设置了host,port,user,pwd等信息。

使用Charles抓包发现，macaca发出的请求中只有第一个create session的请求携带了Authentication，后面的请求都没有Authentication认证，导致服务器返回了401，case执行失败。

![request1](https://user-images.githubusercontent.com/9957802/50951120-0d9e7480-14e7-11e9-9749-ba4c02791df5.png)

![request2](https://user-images.githubusercontent.com/9957802/50951139-20b14480-14e7-11e9-9900-a33c0fd89325.png)

调查发现 macaca-wd模块中webdriver.js中删除了了url中的auth信息，导致最终认证失败。经过测试发现注释掉这一行就能正常运行。不明白为什么要delete这个auth?
https://github.com/macacajs/macaca-wd/blob/master/wd/lib/webdriver.js#L25

**Comment by yihuineng** [comment]
@megolee 感谢反馈，未能复现该问题，由于时间久远，先关闭了，有问题可再次反馈

**Comment by yihuineng** [comment]
close
