### ISSUE TITLE
macaca-wd url切换时，cookie丢失了

### ISSUE THREAD

**Issue by sharon0571** [macacajs/macaca-wd#73]
业务场景需要登录，先登录，后get至目标地址，cookie为空跳至登录
部分主要代码：
var driver = wd.promiseChainRemote({
    host: 'localhost',
    port: process.env.MACACA_SERVER_PORT || 3456
  })
const urlTemp =
          'https://pre-air.1688.com/apps/alim/star-conquerors-hysc/spa-alipay.html'

    const url =
    'https://pre-air.1688.com/apps/alim/star-conquerors-hysc/spa-alipay.html' 
driver.get(`${url}`, { preserveCookies: true })
      .elementByCss(
        '#welcome-page > div.login-blocks.show-login-register-link > a.show-pwd-login-link'
      )
      .click()
      .elementById('fm-login-id')
      .sendKeys(username)
      .elementById('fm-login-password')
      .sendKeys(password)
      .elementByCss('#login-form > div.fm-btn > button')
      .click()
  })
it('页面跳转', async function () {
      console.log( await driver.allCookies())
      driver.get(`${url}`, { preserveCookies: true })
      console.log( await driver.allCookies())
    })
第二个driver.allCookies()返回为空

![image](https://user-images.githubusercontent.com/42926677/55725725-da657600-5a40-11e9-8506-6176df6da4dd.png)

**Comment by paradite** [comment]
@sharon0571 请问是什么environment？Chrome，iOS，Android，electron还是别的？
electron应该是没问题的，有test你可以参考：
https://github.com/macacajs/macaca-electron/blob/master/test/controllers.test.js#L262
其他的可能还不支持。
另外一个test最好放到一个`it`里面，跨不同的`it`可能driver会刷新。
