### ISSUE TITLE
Add Documentation Versioning and Release Notes

### ISSUE THREAD

**Issue by jefrydco** [macacajs/macaca-wd#77]
Our company is still using version 2 of this package, I'm a new joiner of that company. It quite hard for me to understand the code if there isn't any documentation of the previous version.

It will very helpful as well if you can tag each of the release commit and add release notes. I checked the latest NPM package version is 3.3.0 but in the Github, there is no release tag.

**Comment by paradite** [comment]
Hey @jefrydco, thanks for the feedback. I will see if I can tag the previous releases and generate some release docs.
